#!/usr/bin/env python3
"""
Customer Churn Prediction Model Training Script
Trains a Random Forest model with SMOTE for class imbalance and logs to MLflow with S3 artifact storage
"""

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score, recall_score, precision_score
from imblearn.over_sampling import SMOTE
import mlflow
import mlflow.sklearn
import boto3
from botocore.exceptions import ClientError
import warnings
warnings.filterwarnings('ignore')

def setup_aws_credentials():
    """Set up AWS credentials from environment variables"""
    # AWS credentials should be set as GitHub secrets
    required_vars = ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_DEFAULT_REGION']
    for var in required_vars:
        if not os.getenv(var):
            raise ValueError(f"Missing required environment variable: {var}")
    
    print("✓ AWS credentials configured from environment variables")
    
def setup_mlflow_s3():
    """Configure MLflow to use SageMaker tracking server with S3 for artifact storage"""
    # Use SageMaker MLflow tracking server
    mlflow.set_tracking_uri("arn:aws:sagemaker:us-west-1:880138931512:mlflow-tracking-server/demodata")
    
    # Set S3 as default artifact root
    os.environ['MLFLOW_DEFAULT_ARTIFACT_ROOT'] = 's3://myawsbucket.3.2025/artifacts/'
    
    # Set additional S3 environment variables for MLflow
    os.environ['MLFLOW_S3_ENDPOINT_URL'] = 'https://s3.amazonaws.com'
    
    # Disable model registry to avoid SageMaker compatibility issues
    os.environ['MLFLOW_DISABLE_MODEL_REGISTRY'] = 'true'
    
def test_s3_connection():
    """Test S3 connection before proceeding"""
    try:
        s3_client = boto3.client('s3')
        # Try to list buckets to test connection
        response = s3_client.list_buckets()
        print("✓ S3 connection successful")
        
        # Check if our bucket exists
        bucket_name = 'myawsbucket.3.2025'
        try:
            s3_client.head_bucket(Bucket=bucket_name)
            print(f"✓ Bucket '{bucket_name}' is accessible")
        except ClientError as e:
            print(f"⚠ Warning: Bucket '{bucket_name}' may not exist or is not accessible: {e}")
            
    except Exception as e:
        print(f"✗ S3 connection failed: {e}")
        raise

def load_and_preprocess_data():
    """Load and preprocess the training data"""
    print("Loading and preprocessing data...")
    
    # Load the training data (generated by preprocessing script)
    try:
        data = pd.read_csv("../exploration-part/data/pre-processed/train_clientes_features.csv")
        print(f"✓ Data loaded successfully. Shape: {data.shape}")
    except FileNotFoundError:
        print("✗ train_clientes_features.csv not found. Please ensure the preprocessing script has run successfully.")
        raise
    
    # Drop non-predictive columns
    cols_to_drop = ['ID_CORRELATIVO', 'CODMES']
    existing_cols_to_drop = [col for col in cols_to_drop if col in data.columns]
    data = data.drop(columns=existing_cols_to_drop)
    print(f"✓ Dropped columns: {existing_cols_to_drop}")
    
    # Encode categorical variables
    le = LabelEncoder()
    categorical_cols = data.select_dtypes(include=['object']).columns.tolist()
    
    for col in categorical_cols:
        if col != 'ATTRITION':  # Don't encode the target variable if it's already numeric
            data[col] = le.fit_transform(data[col].astype(str))
    
    print(f"✓ Encoded categorical columns: {categorical_cols}")
    
    # Check for target variable (you may need to create it based on your business logic)
    if 'ATTRITION' not in data.columns:
        # Create ATTRITION based on business logic (example: high churn indicators)
        # This is a placeholder - adjust based on your actual churn definition
        data['ATTRITION'] = ((data['TOTAL_RECLAMOS'] > data['TOTAL_RECLAMOS'].quantile(0.8)) | 
                            (data['PORC_RECLAMOS'] > 0.5)).astype(int)
        print("✓ Created ATTRITION target variable based on business rules")
    
    # Separate features and target
    X = data.drop(columns=['ATTRITION'])
    y = data['ATTRITION']
    
    print(f"✓ Features shape: {X.shape}")
    print(f"✓ Target distribution: {y.value_counts().to_dict()}")
    
    return X, y

def train_model_with_mlflow(X, y):
    """Train the model and log everything to MLflow"""
    
    with mlflow.start_run(run_name="RandomForest_SMOTE_Production"):
        
        print("\n" + "="*50)
        print("STARTING MODEL TRAINING")
        print("="*50)
        
        # Split the data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )
        
        print(f"✓ Data split - Train: {X_train.shape[0]}, Test: {X_test.shape[0]}")
        
        # Log data info
        mlflow.log_param("train_size", X_train.shape[0])
        mlflow.log_param("test_size", X_test.shape[0])
        mlflow.log_param("n_features", X_train.shape[1])
        mlflow.log_param("class_distribution_before_smote", dict(y_train.value_counts()))
        
        # Apply SMOTE for oversampling
        print("Applying SMOTE for class balancing...")
        smote = SMOTE(random_state=42)
        X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
        
        print(f"✓ SMOTE applied - New training size: {X_train_smote.shape[0]}")
        print(f"✓ Class distribution after SMOTE: {dict(pd.Series(y_train_smote).value_counts())}")
        
        mlflow.log_param("oversampling_method", "SMOTE")
        mlflow.log_param("class_distribution_after_smote", dict(pd.Series(y_train_smote).value_counts()))
        
        # Train Random Forest model
        print("Training Random Forest model...")
        n_estimators = 200
        max_depth = None
        min_samples_split = 2
        min_samples_leaf = 1
        
        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42,
            n_jobs=-1
        )
        
        model.fit(X_train_smote, y_train_smote)
        print("✓ Model training completed")
        
        # Log model parameters
        mlflow.log_param("model_type", "RandomForestClassifier")
        mlflow.log_param("n_estimators", n_estimators)
        mlflow.log_param("max_depth", max_depth)
        mlflow.log_param("min_samples_split", min_samples_split)
        mlflow.log_param("min_samples_leaf", min_samples_leaf)
        mlflow.log_param("random_state", 42)
        
        # Make predictions
        print("Making predictions...")
        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]
        
        # Calculate metrics
        auc = roc_auc_score(y_test, y_proba)
        f1 = f1_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        
        # Log metrics
        mlflow.log_metric("AUC", auc)
        mlflow.log_metric("F1_score", f1)
        mlflow.log_metric("Recall", recall)
        mlflow.log_metric("Precision", precision)
        
        # Print results
        print("\n" + "="*50)
        print("MODEL EVALUATION RESULTS")
        print("="*50)
        
        print(f"AUC Score: {auc:.4f}")
        print(f"F1 Score: {f1:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"Precision: {precision:.4f}")
        
        print("\nConfusion Matrix:")
        cm = confusion_matrix(y_test, y_pred)
        print(cm)
        
        print("\nClassification Report:")
        print(classification_report(y_test, y_pred, target_names=['No Abandona', 'Abandona']))
        
        # Log the confusion matrix as a text artifact
        cm_str = f"Confusion Matrix:\n{cm}\n\nClassification Report:\n{classification_report(y_test, y_pred, target_names=['No Abandona', 'Abandona'])}"
        
        # Save confusion matrix to a temporary file and log it
        with open("confusion_matrix.txt", "w") as f:
            f.write(cm_str)
        mlflow.log_artifact("confusion_matrix.txt")
        os.remove("confusion_matrix.txt")  # Clean up
        
        # Feature importance
        feature_importance = pd.DataFrame({
            'feature': X.columns,
            'importance': model.feature_importances_
        }).sort_values('importance', ascending=False)
        
        print(f"\nTop 10 Most Important Features:")
        print(feature_importance.head(10))
        
        # Save feature importance and log it
        feature_importance.to_csv("feature_importance.csv", index=False)
        mlflow.log_artifact("feature_importance.csv")
        os.remove("feature_importance.csv")  # Clean up
        
        # Skip model logging to avoid registry issues with SageMaker tracking server
        print("\n✓ Experiment logged successfully to MLflow")
        print("  - Metrics, parameters, and artifacts saved")
        print("  - Model logging skipped (SageMaker tracking server limitation)")
        
        # Log additional metadata
        mlflow.log_param("data_source", "train_clientes_features.csv")
        mlflow.log_param("preprocessing_steps", "label_encoding, smote_oversampling")
        mlflow.log_param("artifact_location", "s3://myawsbucket.3.2025/artifacts/")
        
        return model, {
            'auc': auc,
            'f1': f1,
            'recall': recall,
            'precision': precision
        }

def main():
    """Main execution function"""
    print("Customer Churn Prediction Model Training")
    print("="*50)
    
    try:
        # Setup AWS credentials and MLflow S3 configuration
        print("Setting up AWS credentials and MLflow configuration...")
        print("- Using SageMaker MLflow tracking server")
        print("- Using S3 for artifact storage")
        setup_aws_credentials()
        setup_mlflow_s3()
        
        # Test S3 connection
        test_s3_connection()
        
        # Set MLflow experiment
        experiment_name = "Customer_Churn_Production"
        
        # Additional configuration to avoid model registry issues
        os.environ['MLFLOW_TRACKING_INSECURE_TLS'] = 'true'
        
        mlflow.set_experiment(experiment_name)
        print(f"✓ MLflow experiment set: {experiment_name}")
        print("✓ Model registry functionality disabled")
        
        # Load and preprocess data
        X, y = load_and_preprocess_data()
        
        # Train model and log to MLflow
        model, metrics = train_model_with_mlflow(X, y)
        
        print("\n" + "="*50)
        print("TRAINING COMPLETED SUCCESSFULLY!")
        print("="*50)
        print(f"Model Performance Summary:")
        print(f"- AUC: {metrics['auc']:.4f}")
        print(f"- F1 Score: {metrics['f1']:.4f}")
        print(f"- Recall: {metrics['recall']:.4f}")
        print(f"- Precision: {metrics['precision']:.4f}")
        print(f"\nMLflow Tracking URI: {mlflow.get_tracking_uri()}")
        print(f"Artifacts stored in: s3://myawsbucket.3.2025/artifacts/")
        
    except Exception as e:
        print(f"\n✗ Training failed with error: {str(e)}")
        raise

if __name__ == "__main__":
    main() 