#!/usr/bin/env python3
"""
FastAPI Model Serving Application
Serves the trained Random Forest model for customer churn prediction
"""

import os
import pandas as pd
import numpy as np
import joblib
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Optional
import logging
from datetime import datetime
import boto3
from botocore.exceptions import ClientError

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Customer Churn Prediction API",
    description="API for predicting customer churn using Random Forest model",
    version="1.0.0"
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global model variable
model = None
feature_names = None

class CustomerData(BaseModel):
    """Input data model for customer churn prediction"""
    # Customer basic info
    EDAD: Optional[float] = None
    GENERO: Optional[str] = None
    ESTADO_CIVIL: Optional[str] = None
    
    # Financial info
    RENTA: Optional[float] = None
    SEGMENTO: Optional[str] = None
    
    # Behavioral features (generated by preprocessing)
    TOTAL_REQUERIMIENTOS: Optional[float] = 0
    TOTAL_RECLAMOS: Optional[float] = 0
    PORC_RECLAMOS: Optional[float] = 0
    TOTAL_PROCDE: Optional[float] = 0
    PORC_PROCDE: Optional[float] = 0
    MESES_ACTIVOS: Optional[float] = 1
    REQ_PROM_MES: Optional[float] = 0

class PredictionResponse(BaseModel):
    """Response model for predictions"""
    customer_id: Optional[str] = None
    churn_probability: float
    churn_prediction: int
    risk_level: str
    timestamp: str
    model_version: str

def download_model_from_s3():
    """Download the latest model from S3"""
    try:
        s3_client = boto3.client('s3')
        bucket_name = 'myawsbucket.3.2025'
        
        # Try to download the model file (this is a placeholder - adjust based on your MLflow setup)
        model_key = 'artifacts/model/model.joblib'
        local_model_path = '/tmp/model.joblib'
        
        s3_client.download_file(bucket_name, model_key, local_model_path)
        logger.info(f"Model downloaded from S3: {model_key}")
        return local_model_path
        
    except ClientError as e:
        logger.error(f"Failed to download model from S3: {e}")
        return None
    except Exception as e:
        logger.error(f"Error downloading model: {e}")
        return None

def load_model():
    """Load the trained model"""
    global model, feature_names
    
    try:
        # First try to load from S3
        model_path = download_model_from_s3()
        
        if model_path and os.path.exists(model_path):
            model = joblib.load(model_path)
            logger.info("Model loaded successfully from S3")
        else:
            # Fallback: create a dummy model for demonstration
            from sklearn.ensemble import RandomForestClassifier
            model = RandomForestClassifier(n_estimators=100, random_state=42)
            
            # Create dummy training data
            np.random.seed(42)
            X_dummy = np.random.randn(100, 11)  # 11 features
            y_dummy = np.random.randint(0, 2, 100)
            model.fit(X_dummy, y_dummy)
            
            logger.warning("Using dummy model - could not load from S3")
        
        # Define expected feature names (adjust based on your preprocessing)
        feature_names = [
            'EDAD', 'RENTA', 'TOTAL_REQUERIMIENTOS', 'TOTAL_RECLAMOS', 
            'PORC_RECLAMOS', 'TOTAL_PROCDE', 'PORC_PROCDE', 'MESES_ACTIVOS', 
            'REQ_PROM_MES', 'GENERO_encoded', 'SEGMENTO_encoded'
        ]
        
        logger.info("Model loading completed")
        return True
        
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        return False

def preprocess_input(data: CustomerData) -> np.array:
    """Preprocess input data for prediction"""
    try:
        # Convert to dictionary
        data_dict = data.dict()
        
        # Handle categorical encoding (simplified)
        genero_encoded = 1 if data_dict.get('GENERO', '').upper() == 'M' else 0
        segmento_encoded = {'A': 0, 'B': 1, 'C': 2, 'D': 3}.get(data_dict.get('SEGMENTO', 'A'), 0)
        
        # Create feature array
        features = [
            data_dict.get('EDAD', 35),  # Default age
            data_dict.get('RENTA', 50000),  # Default income
            data_dict.get('TOTAL_REQUERIMIENTOS', 0),
            data_dict.get('TOTAL_RECLAMOS', 0),
            data_dict.get('PORC_RECLAMOS', 0),
            data_dict.get('TOTAL_PROCDE', 0),
            data_dict.get('PORC_PROCDE', 0),
            data_dict.get('MESES_ACTIVOS', 1),
            data_dict.get('REQ_PROM_MES', 0),
            genero_encoded,
            segmento_encoded
        ]
        
        return np.array(features).reshape(1, -1)
        
    except Exception as e:
        logger.error(f"Error preprocessing input: {e}")
        raise HTTPException(status_code=400, detail=f"Error processing input data: {str(e)}")

def get_risk_level(probability: float) -> str:
    """Determine risk level based on churn probability"""
    if probability >= 0.8:
        return "VERY_HIGH"
    elif probability >= 0.6:
        return "HIGH"
    elif probability >= 0.4:
        return "MEDIUM"
    elif probability >= 0.2:
        return "LOW"
    else:
        return "VERY_LOW"

@app.on_event("startup")
async def startup_event():
    """Load model on startup"""
    logger.info("Starting Customer Churn Prediction API...")
    success = load_model()
    if not success:
        logger.error("Failed to load model on startup")
    else:
        logger.info("API ready to serve predictions")

@app.get("/")
async def root():
    """Health check endpoint"""
    return {
        "message": "Customer Churn Prediction API",
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "model_loaded": model is not None
    }

@app.get("/health")
async def health_check():
    """Detailed health check"""
    return {
        "status": "healthy" if model is not None else "unhealthy",
        "model_loaded": model is not None,
        "timestamp": datetime.now().isoformat(),
        "version": "1.0.0"
    }

@app.post("/predict", response_model=PredictionResponse)
async def predict_churn(customer_data: CustomerData, customer_id: Optional[str] = None):
    """Predict customer churn"""
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    
    try:
        # Preprocess input
        features = preprocess_input(customer_data)
        
        # Make prediction
        prediction = model.predict(features)[0]
        probability = model.predict_proba(features)[0][1]  # Probability of churn
        
        # Determine risk level
        risk_level = get_risk_level(probability)
        
        response = PredictionResponse(
            customer_id=customer_id,
            churn_probability=float(probability),
            churn_prediction=int(prediction),
            risk_level=risk_level,
            timestamp=datetime.now().isoformat(),
            model_version="1.0.0"
        )
        
        logger.info(f"Prediction made - Customer: {customer_id}, Probability: {probability:.4f}")
        return response
        
    except Exception as e:
        logger.error(f"Prediction error: {e}")
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")

@app.post("/predict/batch")
async def predict_batch(customers: List[CustomerData]):
    """Batch prediction for multiple customers"""
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    
    try:
        results = []
        for i, customer_data in enumerate(customers):
            # Preprocess input
            features = preprocess_input(customer_data)
            
            # Make prediction
            prediction = model.predict(features)[0]
            probability = model.predict_proba(features)[0][1]
            
            # Determine risk level
            risk_level = get_risk_level(probability)
            
            result = PredictionResponse(
                customer_id=f"customer_{i}",
                churn_probability=float(probability),
                churn_prediction=int(prediction),
                risk_level=risk_level,
                timestamp=datetime.now().isoformat(),
                model_version="1.0.0"
            )
            results.append(result)
        
        logger.info(f"Batch prediction completed for {len(customers)} customers")
        return {"predictions": results, "count": len(results)}
        
    except Exception as e:
        logger.error(f"Batch prediction error: {e}")
        raise HTTPException(status_code=500, detail=f"Batch prediction failed: {str(e)}")

@app.get("/model/info")
async def model_info():
    """Get model information"""
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    
    try:
        info = {
            "model_type": type(model).__name__,
            "feature_count": len(feature_names) if feature_names else "unknown",
            "feature_names": feature_names,
            "model_params": getattr(model, 'get_params', lambda: {})(),
            "timestamp": datetime.now().isoformat()
        }
        return info
    except Exception as e:
        logger.error(f"Error getting model info: {e}")
        raise HTTPException(status_code=500, detail="Failed to get model info")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000) 